:table-caption!:
= PushButton Switch Group (PGSG)

A virtual *PushButtonSwitchGroup* (*PBSG*) device:

* Behaves like a keypad with multiple buttons, where:
** Only one button can be active at any time.
** An optional *default button* is activated if no other button is active.
* Each button has a corresponding *VswWithToggle* child devices.
* The state of the PBSG and its Child devices is continuously reconciled.
** PBSG methods include `activate(button)`, `deactivate(button)`, `push(buttonNumber)`.
** Child devices support `on()`, `off()` and `push()` | `toggle()`.

== PARKED

 // Notes:
 //   - getObjectClassName(Object obj)


== What is a PBSG?

A PBSG is a Hubitat-compatible virtual device where ...

=== The client provides ...

buttons `(required)`::
A list of button names.

defaultButton `(optional)`::
A button (from the buttons list) that becomes active if no other PBSG button is active.

=== The virtual device ensures...

* Only one button is active at any time.
* The defaultButton (if specified) is activated when no other button is active.
* One child VSW exists per button.
* Child VSW state is updated when the PBSG state changes.
* PBSG state is updated when child VSWs are turned on or off.

=== Advanced device features include ...

* Integration with LUX sensors
* Integration with Motion sensors
* A companion demonstration application that illustrates device creation AND facilitates automatically-generated test scripts.
* A custom dashboard cell (FUTURE)

== Why use a PBSG?

* A PBSG realizes a mutually-exclusive collection of buttons and corresponding switches.
* Use cases include: Managing Hubitat modes, Managing per-room scenes, etc.
* The PBSG can support Hubitat's `pushable` interface and concurrently facilitate Alexa integration (which is limited to turn on / turn off).

== How are PBSGs defined?

The structure of a PBSG can be defined:

. Using the device drilldown page in the Hubitat GUI.
. In code using available API calls.

== What Components are Provided ?

TBD

== PARKED

lPBSG.groovy::
Hubitat functions that can be incorporated into downstream applications
via `#include wesmc.lPBSG`. The functions collectively implement
*PushButton Switch Group (PBSG)* instances where each PBSG instance:

* Creates and manages a group of Virtual Switches (VSWs) - one per _pushbutton_.
* Turns off peer VSWs when one of the participating VSWs is turned on.
* Turns on a default VSW (if specified) when no participating VSW is turned on.
* Provides a `turnOnPrior()` method to restore the last active VSW.

Demo-PBSG.groovy::
Hubitat-compatible application source code that illustrates:

* Creating PBSG instances via a GUI.
* Creating PBSG instances via a configuration Map.
* Pushbutton methods and callbacks.

lPBSG.zip::
A _Hubitat Bundle_ for installing the `lPBSG.groovy` Hubitat library and the
`Demo-PBSG.groovy` Hubitat application.

packageManifest.json::
Provided to install the lPBSG.zip bundle via the moniker `WesMC-PBSGLibrary` in
https://hubitatpackagemanager.hubitatcommunity.com/[Hubitat Package Manager (HPM)].

== Creating PBSG Instances
The `Demo-PBSG` application illustrates how PBSG instances can be created
(1) by soliciting data via an Application user interfaces or (2) by providing
in-kind data via a configuration Map instance.

== Rationale for Technology Choices

=== Use of a Callback Function in lieu of emitting an Event
TBD

=== One Child VSW per PBSG "Button"

PROS::

* Unlike pushable buttons or scenes, VSWs can be turned on|off by
Alexa, Google Home, AirPlay, Hubitat rules, peer applications, etc.

CONS::

* At scale, creating several PBSG instances (each with
fully-independent buttons) results in a plethora of VSWs. As of Q2'24, newly
created VSWs have `Enable debug logging` and `Enable descriptionText logging`
enabled with no API for creating quieter VSWs.

=== Each PBSG Instance Name has a top-level Hubitat State Map Entry

PROS::

* Each PBSG instance is an independent Map - which can be treated like an
instance of a class (even though operating in Hubitat's sandboxed environment).

* Operations on a PBSG instance are efficient thanks to the use of atomicState
and atomicState.updateMapValue(...).

* Downstream pseudo-classes can be created by expanding the keys in a PBSG's
instance Map. For example: Room's may have mutually-independent scenes where
each Room instance is a PBSG instance with extra keys and methods that operate
on those keys.

CONS::

* PBSG Names must be sufficiently unique to avoid collisions in the App's
state|atomicState.

== OTHER STUFF

=== OVERVIEW
.Conceptually, a PBSG has:
[width="100%", frame="none", grid="none", cols=">15h,<85"]
|===
|buttons |An ArrayList of all the buttons managed by the PBSG
|active |The button that is currently 'on' +
(can be null if there is no dflt button)
|dflt |The button that is turned 'on' if active becomes null +
(can be 'not_applicable')
|lifo |
The list of 'off' buttons where the most recently +
turned off button is the "last in" - facilitating the "activateLastActive" command.
|===

.Subscribable Events
----
     PBSG state (issued for any state change):
       [
         == MINIMAL/COMPREHENSIVE SUMMARY OF STATE
                     active: String or null  - 'on' button
                       lifo: ArrayList       - 'off' buttons
                       dflt: String or null  - 'dflt' button
         == FOR `PushableButton` CAPABILITY
            numberOfButtons: Integer         - N
                     pushed: Integer         - Position 1..N
         == FOR CONVENIENCE
                    buttons: ArrayList       - 'all' buttons
           buttonToPosition: Map             - button name → 1..N
                    display: String          - Log-friendly state
       ]
     PushableButton (issued when cited fields change):
       [
            numberOfButtons: Integer         - N
                     pushed: Integer         - Position 1..N
       ]
----

.VERY IMPORTANT
----
     The ArrayList implementation of "lifo" is inverted !!!
       - push() is expected to PREPEND an item which pop() retrieves
       - Instead push() APPENDS an item which pop() retrieves
     The 'display' String provides a visual summary active & lifo
----

== USAGE OF CONCURRENT HASH MAP

=== Competition for PBSG static data
* Manual update via Hubitat UI
* Programmatic update via config()

=== Competition for PBSG dynamic data
* Requests on the PBSG itself (from the parent, from events)
* Actions on the VSWs (fielded by the parent)

=== Reboot Challenges
* No entries survive a hub reboot; so, state must be rebuilt.
* Each PBSG has a Concurrent State Map (csm) stored in perPbsgState
at key device.idAsLong.
** Concurrency extends to operations on this inner Map.
** To abbreviate 'concurrentState', 'ccs' is used.
** Treatment wrt the following is TBD:

NOTE: The ConcurrentHashMap `perPbsgState` is used in lieu of `state`
or `atomicState`.