= Multiple Page Applications

This article distills material introduced in https://community.hubitat.com/t/dynamic-multi-page-app-that-edits-a-nested-map/120338/2[MikeNYC's Hubitat Community Posting.]

== Definitions

[frame="none", grid="none", cols=">20h,<80"]
|===
|Function |A Groovy method
|Page |A form used to solicit client input data.
|Dynamic Page |A special type of *Page* that can be embedded in a *Function*, presented conditionally, and/or leverage `hrefs` to _jump to_ other *Pages* - optionally passing data (via a `param` Map).
|Section Block |A subdivision within a *Page*.
|Preferences |A code block that lists the appliation's *Pages* and *Dynamic Pages* and optionally control aspects of page navigation.
|===

== Rules

. The *Preferences* block should include, *Functions* that:
    * Define a *Page*
    * Are the target of a `nextPage` expression.
    * Are the target `page:` in an `href` expression.
. All *Functions* referenced in a *Page* needs to:
    * Contain a *Page* +
    OR
    * Finish by referencing a *Function* containing a *Page*. +
    ** If a *Function* peforms a calculation, it can be written as an intermediate *Page* - i.e., invoked by a predecessor *Page* and targeting a `next`/`href` *Page*.
. *Pages* embedded in a *Function* DO NOT need to be listed in *Preferences*.
. The first *Page* (*Function*) presented to a client should appear first in the *Preferences*.
. Each `param` referenced in an `href`, must be in the form of a `map`, even if there is only one key. +
Examples:
    * `params: [key : mapKey, move : "down"]`
    * `params: [key : mapKey]`
. The Function being called DOES NOT need to use "param" as the input variable.

.href
[indent=4]
----
href(
  name: "toMoveUp",
  title: "Move Up",
  page: "moveLogicFunction",            // Page targeted by the href.
  params: [key : mapKey, move : "up"],  // 'key' and 'move' are params.
  description: "↑",
  width: 2
)
----
.Target Function
[indent=4]
----
def moveLogicFunction(differentName) {
  def name = differentName.key
  def upOrDown = differentName.move
}
----

[start=7]
. *Pages* within *Functions* must be *Dynamic Pages*.
. All required fields must be populated BEFORE using the brower's "back" button OR using an `href` (to go to another page).

NOTE: An "error page" can be used to enforce required information and redirect the client.

[start=9]
. The UI should include `cancel` and `next` buttons as necessary.

* `Done` usually moves to the final *Page*; but, this technique DOES NOT work if the last page is generated by a Function. [Alternately, A `next` *Page* (_intermediate page_) can include the function that generates the last page.]

* Browser `back` buttons DO NOT work when the last page is Function generated. [Alternately, create a `cancel` *href* that references the page with the function that generates the final page.]
